# Generated by Django 6.1.1 on 2026-09-09 06:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('hex_code', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, e.g. #FF0000.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='products.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'color_name'), name='unique_product_color')],
            },
        ),
    ]
