# Generated by Django 6.1.1 on 2026-09-09 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.productcolor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.productsize')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('color__isnull', False), ('size__isnull', False)), fields=('product', 'size', 'color'), name='unique_variant_size_and_color'), models.UniqueConstraint(condition=models.Q(('color__isnull', True)), fields=('product', 'size'), name='unique_variant_size_only'), models.UniqueConstraint(condition=models.Q(('size__isnull', True)), fields=('product', 'color'), name='unique_variant_color_only'), models.CheckConstraint(condition=models.Q(('size__isnull', False), ('color__isnull', False), _connector='OR'), name='variant_requires_size_or_color')],
            },
        ),
    ]
